name: test

on:
  schedule:
    - cron: '50 18 * * *'
  workflow_dispatch:

permissions:
    contents: read
    actions: write

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
   
    - name: Pull and run Docker image
      run: |
        docker run --rm -d \
          --shm-size 4g \
          --name ${{ secrets.CONTAINER_NAME }} \
          ${{ secrets.DOCKER_IMAGE }}

    - name: Log Docker container and send to Discord
      run: |
        while true; do
          docker logs ${{ secrets.CONTAINER_NAME }} > ${{ secrets.CONTAINER_NAME }}_logs.txt
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$(cat ${{ secrets.CONTAINER_NAME }}_logs.txt)\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
          sleep 300
        done

    - name: app
      run: |
        chmod +x entrypoint.sh

    - name: app run
      run: |
        bash entrypoint.sh
