name: test

on:
  schedule:
    - cron: '50 18 * * *'
  workflow_dispatch:

permissions:
    contents: read
    actions: write

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
   
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Pull and run Docker image
      run: |
        CONTAINER_ID=$(docker run --rm -d --shm-size 4g --name ${{ secrets.CONTAINER_NAME }} ${{ secrets.DOCKER_IMAGE }})
        echo "Container ID: $CONTAINER_ID"
        echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV

    - name: Log Docker container and send to Telegram
      run: |
        while true; do
          DATE=$(date +'%d-%m-%Y')
          LOG_FILE="${{ secrets.CONTAINER_NAME }}_${DATE}_logs.txt"
          LOGS=$(docker logs ${{ secrets.CONTAINER_NAME }} 2>/dev/null || docker logs $CONTAINER_ID)
          echo "$LOGS" > $LOG_FILE
          echo "Logs captured:"
          cat $LOG_FILE
          
          # Send logs to Telegram
          curl -F document=@$LOG_FILE \
               https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}
          
          echo "Logs sent to Telegram"
          sleep 300
        done
